### ISSUE TITLE
Add GEM data to ppm config

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-africa/pypsa-africa#689]
## Describe the feature you'd like to see
Currently, PyPSA-Earth uses only a limited amount of available powerplant data:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/313ef0b9434df49d7725f6e17e11b74d73800171/configs/powerplantmatching_config.yaml#L17-L29

Let's try to add the existing global gas powerplant tracker database:
https://powerplantmatching.readthedocs.io/en/latest/api/powerplantmatching.data.GGPT.html

In future, we might want to add also the [coal powerplant data ](https://github.com/PyPSA/powerplantmatching/issues/80)and the GEM solar + wind data

**Comment by Tomkourou** [comment]
@pz-max I was the one to add GEM_GPPT to the powerplantmatching module. Do you know what the problem with it was and why it was not incorporated? Happy to take this on and add the other GEM datasets.

**Comment by pz-max** [comment]
Yep, the GEM_GPPT was not working. Tests didn't trigger that it was breaking because it wasn't included. I rewrote it afterwards in a new PR where we renamed that to `GPPT`. Would be a great contribution @Tomkourou :)

**Comment by Tomkourou** [comment]
I just saw that the link I was using to programmatically access their dataset went dead. I guess that's partly why it didn't work. You also have a repo I see. Would it be worth downloading all the datasets into that repo, concatenating them that way we can call a single url?

**Comment by pz-max** [comment]
@Tomkourou feel free to add a PR on my repo to add the Coal Data. Adding it as a separate file would be my current prefered option as it would not change any past dev and provides some flexibility (e.g. you could disable certain GEM data with that approach)

When you access the GEM interface, tehre is also a data download link.
We could use this link also instead of uploading the data to my repo.
However, the latter (as done for GGPT) might be more stable.

**Comment by Tomkourou** [comment]
@pz-max I have made a PR and added all the latest GEM datasets available. I also just checked the GPD dataset and realised that it needs updating so we should also make a PR for that.

**Comment by pz-max** [comment]
Just accepted thanks for pinging me @Tomkourou  :+1:

**Comment by pz-max** [comment]
We can now add here all the "new powerplantmatching" sources.
The new sources are coming from: https://github.com/PyPSA/powerplantmatching/pull/110
